version: '3'

services:
  ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: pure-ftpd-1
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./data:/home"
      - "./passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FPT_USER_HOME: /home/username
    command: /run.sh -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -s -A -j -Z -H -4 -E -R -X -x

  web:
    image: php:7.4-apache
    volumes:
      - "./html:/var/www/html"
    ports:
      - "8080:80" 
    environment:
      FTP_HOST: "ftp"
      FTP_USER_NAME: "ftpuser"
      FTP_USER_PASS: "ftppass"